ignore-creative: false # Can creative player start fight music
run-away-clock: 5 # The time after the music cancel when they stop fighting

ignore-playervsplayer: false # Do you ignore player vs player

music:
  entityType:
    entityName:
      sound:
      - music 0 # music -> is the music name and 0 -> duration