ignore-creative: true #Can creative player start fight music
run-away-time: 15 #The time after the music cancel when they stop fighting
disable-music: #entity that you don't want epic music. You don't need epic music for chicken !
  - villager
  - chicken
  - cow
  - squid
  - sheep
  - rabbit
  - pig
  - parrot
  - ocelot
  - bat
  - horse

mcjukebox:
  fade-time: 3 #fading time in second when using mcjukebox
  channel: "default" #What channel ? If you don't know leave it to default
  volume: 100 #Music volume (max 100)


ignore-playervsplayer: false #Do you ignore player vs player

default-battlesound:
  - "https://audio.jukehost.co.uk/p/e1ed6c25e972c60066f8d81e2533b75cdf6261e7/2c55e818227" #Just put your sound here, if you use minecraft sound it can be custom.creeper

music:
  sound:
    - "Scary_Monsters_And_Nice_Sprites.nbs"